name: guide_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image
  - h5py
  - imageio
  - json5
  - openpyxl
  - pickleshare
  - pillow
  - python-dateutil
  - tqdm
  - tensorboard
  - pip
  - pip:
      - pytorchcv
      - zuko
      - python_hostlist

